warm:
  - 'red'
  - 'gold'
  - 'peru'
  - 'orangered'
  - 'tomato'
  - 'coral'
  - 'salmon'
  - 'crimson'
  - 'firebrick'
  - 'darkorange'
cool:
  - 'forestgreen'
  - 'cyan'
  - 'darkviolet'
  - 'teal'
  - 'deepskyblue'
  - 'dodgerblue'
  - 'royalblue'
  - 'slateblue'
  - 'mediumseagreen'
  - 'turquoise'