#file: noinspection YAMLSchemaValidation
env_id: 'deep-sea-treausure-v0'
ref_point: [ -100.0, -100.0 ]
file_prefix: 'dst'
actions:
  0: 'up'
  1: 'down'
  2: 'left'
  3: 'right'
action_mapping:
  - (-1, 0)
  - (1, 0)
  - (0, -1)
  - (0, 1)
reward_dim: (2,)
observations_features: ['y', 'x']
observations_high: [11, 11]
observations_low: [0, 0]
gamma: 1.0
num_steps: 50
tolerance: 0
eval_episodes: 1
