#file: noinspection YAMLSchemaValidation
env_id: 'mo-reacher-v4'
ref_point: [-50, -50, -50, -50]
file_prefix: 'reacher'
actions:
  0: '(-1, -1)'
  1: '(-1, 0)'
  2: '(-1, 1)'
  3: '(0, -1)'
  4: '(0, 0)'
  5: '(0, 1)'
  6: '(1, -1)'
  7: '(1, 0)'
  8: '(1, 1)'
reward_dim: (4,)
observations_features: ['cos(th1)', 'cos(th2)', 'sin(th1)', 'sin(th2)', 'angvel1', 'angvel2']
observations_high: [ [ 40, -50, -50, -50 ], [ -50, 40, -50, -50 ], [ -50, -50, 40, -50 ], [ -50, -50, -50, 40 ] ]
observations_low:  [ [ -50, -50, -50, -50 ], [ -50, -50, -50, -50 ], [ -50, -50, -50, -50 ], [ -50, -50, -50, -50 ] ]
gamma: 0.99
tolerance: 1e-15
eval_episodes: 100